version: '3'

services:
  nginx:
    image: nginx:1.17.9
    ports:
      - 88:80
    # - 443:443
    volumes:
      - ./src:/var/www:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8
    restart: on-failure:3
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www:delegated
    networks:
      - app-network

  redis:
    image: redis:6.0-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redisdata:/data
    networks:
      - app-network
    restart: on-failure:3

volumes:
  redisdata:
    driver: local
  mysqldata:
     driver: local

networks:
  app-network:
    driver: bridge
